version: "3.7"

services:
  webserver:
    build:
      context: ./bin
      dockerfile: ${PHPVERSION}
    restart: 'always'
    ports:
      - "8001-8010:80"
    #links: 
    #  - database
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  
  lb:
    image: dockercloud/haproxy
    links:
      - webserver
    ports:
      - '8000:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock